site_title = "LibSignal-SignalArxiv"
limit_days = 7
cache_url = "https://github.com/DaRL-LibSignal/SignalArxiv/cache.json"

[[sources]]
limit = 150
category = "cs.SY"
title = "Systems and Control"

[[sources]]
limit = 150
category = "cs.LG"
title = "Machine Learning"

[[sources]]
limit = 150
category = "cs.AI"
title = "Artificial Intelligence"

[[sources]]
limit = 150
category = "cs.CE"
title = "Computational Engineering"

[scripts]
highlight_title = "scripts/highlight_title.rhai"
highlight_author = "scripts/highlight_author.rhai"
highlight_conference = "scripts/highlight_conference.rhai"
